### ISSUE TITLE
Create method: appendDateAndUsername(String text);

### ISSUE THREAD

**Issue by jpierpont** [jminor717/website4#1]
Adds Date and Time to beginning of message.
Ex: 4:32 PM Username: Message

**Comment by jminor717** [comment]
i think what would be easyest to do with the way im doing the posts is to turn each post into an object with   2 string one for the username and one for the post text and store the time as the epoch time https://stackoverflow.com/questions/13731218/how-do-i-get-milliseconds-from-epoch-1970-01-01-in-java
